import { Manrope } from "next/font/google";
import "./globals.css";

import { Toast } from "@heroui/react";

export const metadata = {
  title: "SkillSphere",
  description: "Generated by create next app",
};

const manropeFont = Manrope({
  variable: "manrope-font",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className={`${manropeFont.className} overflow-x-hidden`}>
        {children}
        <Toast.Provider placement="top" />
      </body>
    </html>
  );
}
